name: Release

on:
  push:
    branches: [main, "v*"]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Release
    runs-on: [self-hosted, general-ubuntu]
    env:
      NODE_MODULES_CACHE_BUCKET_NAME: core-servi-github-actions-build-cach20240118162152102700000001
      NODE_MODULES_CACHE_BUCKET_REGION: us-east-1
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TURO_GITHUB_WORKFLOWS_APP_ID }}
          private-key: ${{ secrets.TURO_GITHUB_WORKFLOWS_APP_PRIVATE_KEY }}
          # Creates a token for all the repositories in the current owner's (turo) installation
          # See this for more information: https://github.com/actions/create-github-app-token?tab=readme-ov-file#create-a-token-for-all-repositories-in-the-current-owners-installation
          owner: ${{ github.repository_owner }}
      - uses: open-turo/actions-node/release@v6
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          npm-auth-token: ${{ secrets.ARTIFACTORY_NPM_AUTH_TOKEN }}
          s3-bucket-name: ${{ env.NODE_MODULES_CACHE_BUCKET_NAME }}
          s3-bucket-region: ${{ env.NODE_MODULES_CACHE_BUCKET_REGION }}
