name: Security scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  code-scan:
    name: Code scan
    runs-on: [self-hosted, general-ubuntu]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: open-turo/actions-security/static-analysis@v3
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
